### ISSUE TITLE
cdn.antlr3.org hacked for spam

### ISSUE THREAD

**Issue by azrdev** [antlr/website-antlr3#3]
as someone on irc noted, <cdn.antlr3.org> is used for spam, e.g. `https://cdn.antlr3.org/p5soqrlzfli8/14-kelton-stiedemann/read-9781847156105-jackpot.pdf`

**Comment by parrt** [comment]
not sure how they do this, @azrdev as my host records for antlr3.org look fine.

**Comment by azrdev** [comment]
@parrt thx for caring (so quickly)!

Maybe it has something to do with step 2 in <https://help.github.com/articles/quick-start-setting-up-a-custom-domain/>?
> Configuring your custom domain with your DNS provider without adding your custom domain to GitHub could result in someone being able to host a site on one of your subdomains

If I get any more clues, I'll follow up here.

**Comment by parrt** [comment]
That is so weird, @azrdev, `www.antlr3.org` is set as my custom domain.

**Comment by parrt** [comment]
I tried turning on  https  and disallowing any subdomains other than www.  now I wait for DNS to propagate I guess.

**Comment by parrt** [comment]
host records look like this: 
<img width="426" alt="screen shot 2018-11-07 at 12 51 25 pm" src="https://user-images.githubusercontent.com/178777/48160115-debc1600-e28b-11e8-847b-47871dd2b51a.png">

See any issues?

**Comment by parrt** [comment]
Ah. here is the key link: https://securityblog.switch.ch/2017/11/14/subdomain-hijacking

**Comment by azrdev** [comment]
glad you figured it out!
